### ISSUE TITLE
Plugin Caused Server Crash (Invalid Argument Exception)

### ISSUE THREAD

**Issue by CoolCuzzy** [platz1de/EasyEdit#102]
Hey so all i did was join the server and all of a sudden the plugin kept sending repeated error messages and the server crashed. Here is the Error

![IMG_1300](https://github.com/platz1de/EasyEdit/assets/51475531/53cdc35c-8520-4769-b765-aae868f65f33)

**Comment by platz1de** [comment]
Which version of the Plugin (exact name of the phar) are you using?

This should be fixed in 7a213a399ccab9acb2eae8d045d7422de255a0e1 (since dev #493)
