### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by gamegam** [platz1de/EasyEdit#109]
Class "platz1de\EasyEdit\environment\MainThreadHandler" not found"

PM: 5.13

**Comment by gamegam** [comment]
[23:51:59.370] [EasyEdit editing thread/CRITICAL]: Error: "Class "pocketmine\network\mcpe\protocol\serializer\PacketSerializerContext" not found" (EXCEPTION) in "C:/Users/Administrator/Desktop/server/plugins/EasyEdit.phar/src/platz1de/EasyEdit/world/blockupdate/InjectingData" at line 20
--- Stack trace ---
  #0 C:/Users/Administrator/Desktop/server/plugins/EasyEdit.phar/src/platz1de/EasyEdit/world/blockupdate/InjectingSubChunkController(38): platz1de\EasyEdit\world\blockupdate\InjectingData->__construct(int 15, int 3, int 15)
  #1 C:/Users/Administrator/Desktop/server/plugins/EasyEdit.phar/src/platz1de/EasyEdit/world/ChunkController(104): platz1de\EasyEdit\world\blockupdate\InjectingSubChunkController->moveTo(int 244, int 63, int 246)
  #2 C:/Users/Administrator/Desktop/server/plugins/EasyEdit.phar/src/platz1de/EasyEdit/world/blockupdate/InjectingSubChunkController(52): platz1de\EasyEdit\world\ChunkController->setBlock(int 244, int 63, int 246, int 20481500)
  #3 C:/Users/Administrator/Desktop/server/plugins/EasyEdit.phar/src/platz1de/EasyEdit/task/editing/EditTaskHandler(181): platz1de\EasyEdit\world\blockupdate\InjectingSubChunkController->setBlock(int 244, int 63, int 246, int 20481500)
  #4 C:/Users/Administrator/Desktop/server/plugins/EasyEdit.phar/src/platz1de/EasyEdit/task/editing/CutTask(62): platz1de\EasyEdit\task\editing\EditTaskHandler->changeBlock(int 244, int 63, int 246, int 20481500)
  #5 C:/Users/Administrator/Desktop/server/plugins/EasyEdit.phar/src/platz1de/EasyEdit/selection/constructor/CubicConstructor(42): platz1de\EasyEdit\task\editing\CutTask->platz1de\EasyEdit\task\editing\{closure}(int 244, int 63, int 246)
  #6 C:/Users/Administrator/Desktop/server/plugins/EasyEdit.phar/src/platz1de/EasyEdit/task/editing/SelectionEditTask(134): platz1de\EasyEdit\selection\constructor\CubicConstructor->moveTo(int 255)
  #7 C:/Users/Administrator/Desktop/server/plugins/EasyEdit.phar/src/platz1de/EasyEdit/task/editing/SelectionEditTask(86): platz1de\EasyEdit\task\editing\SelectionEditTask->executeEdit(object platz1de\EasyEdit\task\editing\EditTaskHandler#62171, int 255)
  #8 C:/Users/Administrator/Desktop/server/plugins/EasyEdit.phar/src/platz1de/EasyEdit/task/ExecutableTask(39): platz1de\EasyEdit\task\editing\SelectionEditTask->executeInternal()
  #9 C:/Users/Administrator/Desktop/server/plugins/EasyEdit.phar/src/platz1de/EasyEdit/thread/EditThread(76): platz1de\EasyEdit\task\ExecutableTask->run()
  #10 pmsrc/src/thread/CommonThreadPartsTrait(117): platz1de\EasyEdit\thread\EditThread->onRun()
  #11 (): pocketmine\thread\Thread->run()
--- End of exception information ---

**Comment by platz1de** [comment]
This issue has already been solved, use v3.1.0
