### ISSUE TITLE
wand cmd does not work and instead console is spammed with errors.

### ISSUE THREAD

**Issue by randogaming6252** [platz1de/EasyEdit#110]
self explanitory. installed and ran, tried wand cmd and the console was spammed with errors. this error is on the v5.13.0 pmmp server.

**Comment by platz1de** [comment]
Please provide a crash report (or error + stack trace) and which version of EasyEdit you're using

**Comment by S3b4sM** [comment]
this is error 
`2024-03-17 [17:20:17.823] [EasyEdit editing thread/CRITICAL]: Error: "Class "pocketmine\network\mcpe\protocol\serializer\PacketSerializerContext" not found" (EXCEPTION) in "/home/container/plugins/EasyEdit.phar/src/platz1de/EasyEdit/world/blockupdate/InjectingData" at line 20
--- Stack trace ---
  #0 /home/container/plugins/EasyEdit.phar/src/platz1de/EasyEdit/world/blockupdate/InjectingSubChunkController(38): platz1de\EasyEdit\world\blockupdate\InjectingData->__construct(int 1, int 4, int 4)
  #1 /home/container/plugins/EasyEdit.phar/src/platz1de/EasyEdit/world/ChunkController(104): platz1de\EasyEdit\world\blockupdate\InjectingSubChunkController->moveTo(int 16, int 68, int 68)
  #2 /home/container/plugins/EasyEdit.phar/src/platz1de/EasyEdit/world/blockupdate/InjectingSubChunkController(52): platz1de\EasyEdit\world\ChunkController->setBlock(int 16, int 68, int 68, int 20481500)
  #3 /home/container/plugins/EasyEdit.phar/src/platz1de/EasyEdit/task/editing/EditTaskHandler(181): platz1de\EasyEdit\world\blockupdate\InjectingSubChunkController->setBlock(int 16, int 68, int 68, int 20481500)
  #4 /home/container/plugins/EasyEdit.phar/src/platz1de/EasyEdit/task/editing/SetTask(65): platz1de\EasyEdit\task\editing\EditTaskHandler->changeBlock(int 16, int 68, int 68, int 20481500)
  #5 /home/container/plugins/EasyEdit.phar/src/platz1de/EasyEdit/selection/constructor/CubicConstructor(42): platz1de\EasyEdit\task\editing\SetTask->platz1de\EasyEdit\task\editing\{closure}(int 16, int 68, int 68)
  #6 /home/container/plugins/EasyEdit.phar/src/platz1de/EasyEdit/task/editing/SelectionEditTask(134): platz1de\EasyEdit\selection\constructor\CubicConstructor->moveTo(int 33)
  #7 /home/container/plugins/EasyEdit.phar/src/platz1de/EasyEdit/task/editing/SelectionEditTask(86): platz1de\EasyEdit\task\editing\SelectionEditTask->executeEdit(object platz1de\EasyEdit\task\editing\EditTaskHandler#128788, int 33)
  #8 /home/container/plugins/EasyEdit.phar/src/platz1de/EasyEdit/task/ExecutableTask(39): platz1de\EasyEdit\task\editing\SelectionEditTask->executeInternal()
  #9 /home/container/plugins/EasyEdit.phar/src/platz1de/EasyEdit/thread/EditThread(76): platz1de\EasyEdit\task\ExecutableTask->run()
  #10 pmsrc/src/thread/CommonThreadPartsTrait(117): platz1de\EasyEdit\thread\EditThread->onRun()
  #11 (): pocketmine\thread\Thread->run()
--- End of exception information ---`

**Comment by platz1de** [comment]
This is fixed in Version 3.1.0 us that
Still waiting for poggit to finally accept the release...
