### ISSUE TITLE
Shapes only generate with minimum value of 32

### ISSUE THREAD

**Issue by skips8771** [platz1de/EasyEdit#111]
Every time I generate a shape with //cyl or //sphere or any of the others, they only generate with a minimum value of somewhere around 32 or more. This is frustrating when trying to build on a smaller scale. Any ideas?

**Comment by platz1de** [comment]
This might be resolved in v3.1.0 (poggit release was a few hours ago)

**Comment by skips8771** [comment]
Everything works now, thank you!
