### ISSUE TITLE
Copy paste issue

### ISSUE THREAD

**Issue by LIVEGUYS** [platz1de/EasyEdit#112]
When I do //cut than it gone the land I know it's gone ok that's nice but when I do //flip it's flipped also but when I do //paste doesn't show any structure only shows (numbers) blocks has been placed! (Numbers) I means I forgot the blocks how many are there! That's why (numbers) it's shows block has been placed but no structure?

**Comment by LIVEGUYS** [comment]
Update the plugin to API 5.13.0

**Comment by platz1de** [comment]
I can't reproduce this, which version of EasyEdit are you using?
Also is there anything in the console?

**Comment by LIVEGUYS** [comment]
3.1.0 newest update! When I do /paste doesn't show the structure I copied /copy by /flip than i did /paste doesn't work doesn't show in live console I need to check log

**Comment by LIVEGUYS** [comment]
I change the plugin api into 5.12.0 to 5.13.0 in the plugin.yml in easyedit 3.1.0 in this version!

**Comment by LIVEGUYS** [comment]
I did check recently doesn't show anything error in the console and even in the log file

**Comment by platz1de** [comment]
Were you looking up while flipping? If so i'll close this in favor of #116

**Comment by LIVEGUYS** [comment]
Yep flip is not working pls fix same problem

**Comment by LIVEGUYS** [comment]
Same problem
