### ISSUE TITLE
make i18n

### ISSUE THREAD

**Issue by fuyutsuki** [platz1de/EasyEdit#12]
The language can be changed in message.yml, but it is cumbersome to have the user translate the language every time.
So I think it should be changed to use a file for each language.

Examples: ja.yml, en.yml, id.yml

**Comment by platz1de** [comment]
This will be part of the next release (no ETA yet)
(Implemented in cdaf8050c89a09b7426cbf314d764a07824550d0)

If you want to help translate, please refer to [TRANSLATE.md](https://github.com/platz1de/EasyEdit/blob/dev/resources/lang/TRANSLATE.md)
