### ISSUE TITLE
I used standalone '/fill' command and map turned into atlantis

### ISSUE THREAD

**Issue by scuderia666** [platz1de/EasyEdit#121]
![image](https://github.com/user-attachments/assets/5e735468-d001-4ac7-bac5-0741e45c41fb)

**Comment by nxpinhum5326** [comment]
![resim](https://github.com/user-attachments/assets/b9a2ca3b-1306-4adf-b949-d92c07a66543)
Uh oh uh... 💀

**Comment by platz1de** [comment]
The fill command "fills" an area in to the direction you are looking in (e.g. a lake)
You're probably looking for the //set command to set the selected area
