### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by PushkarOP** [platz1de/EasyEdit#15]
I am trying to load this schematics, but it never load, it also doesn't show any error on console also
[hub.zip](https://github.com/platz1de/EasyEdit/files/8588493/hub.zip)

**Comment by platz1de** [comment]
The schematic contained in the zip file works perfectly fine for me, it just takes a while to load it as it contains 81,5M blocks (a few Minutes at maximum depending on your cpu clockspeed), currently no message is sent until it is finished loading.

**Comment by PushkarOP** [comment]
ok let me try again
