### ISSUE TITLE
task crash when importing schematic

### ISSUE THREAD

**Issue by logannn61** [platz1de/EasyEdit#17]
If you create a schematic with easy edit then try to load it, it will not 

02.05 16:52:12 [Server] EasyEdit editing thread/CRITICAL ErrorException: "Undefined array key 0" (EXCEPTION) in "/plugins/EasyEdit.phar/src/platz1de/EasyEdit/schematic/type/SpongeSchematic" at line 83
02.05 16:52:12 [Server] INFO --- Stack trace ---
02.05 16:52:12 [Server] INFO #0 /plugins/EasyEdit.phar/src/platz1de/EasyEdit/schematic/type/SpongeSchematic(83): pocketmine\\errorhandler\\ErrorToExceptionHandler::handle(integer 2, string[21] Undefined array key 0, string[133] phar:///plugins/EasyEdit.phar/src, integer 83)
02.05 16:52:12 [Server] INFO #1 /plugins/EasyEdit.phar/src/platz1de/EasyEdit/schematic/SchematicFileAdapter(44): platz1de\\EasyEdit\\schematic\\type\\SpongeSchematic::readIntoSelection(object pocketmine\\nbt\\tag\\CompoundTag#491, object platz1de\\EasyEdit\\selection\\DynamicBlockListSelection#23)
02.05 16:52:12 [Server] INFO #2 /plugins/EasyEdit.phar/src/platz1de/EasyEdit/task/schematic/SchematicLoadTask(54): platz1de\\EasyEdit\\schematic\\SchematicFileAdapter::readIntoSelection(string[83] /plugin_data/EasyEdit/schematics/, object platz1de\\EasyEdit\\selection\\DynamicBlockListSelection#23)
02.05 16:52:12 [Server] INFO #3 /plugins/EasyEdit.phar/src/platz1de/EasyEdit/thread/EditThread(72): platz1de\\EasyEdit\\task\\schematic\\SchematicLoadTask->execute()
02.05 16:52:12 [Server] INFO #4 pmsrc/src/thread/CommonThreadPartsTrait(93): platz1de\\EasyEdit\\thread\\EditThread->onRun()
02.05 16:52:12 [Server] INFO #5 (): pocketmine\\thread\\Thread->run()
02.05 16:52:12 [Server] INFO --- End of exception information ---

**Comment by platz1de** [comment]
Looks like the file somehow has no or an incomplete palette.
Can you send the schematic file?

**Comment by logannn61** [comment]
Do you have discord because i cant send schematics on github its not supported

**Comment by platz1de** [comment]
yea, platz1de#4456
If you're on the pocketmine discord you should be able to write me a PM

**Comment by platz1de** [comment]
On the dev branch this was unintentionally fixed by afdc5459dbf8f890881b3abcc8de6e178b5bc924.
As only schematics containing unknown blocks are affected, this won't get a separate patch.
The next major version without this bug is expected to be released in about 2 or 3 weeks

**Comment by 18780262934** [comment]
> 在 dev 分支上，这是[afdc545](https://github.com/platz1de/EasyEdit/commit/afdc5459dbf8f890881b3abcc8de6e178b5bc924)无意中修复的。 由于只有包含未知方块的原理图会受到影响，因此不会获得单独的补丁。 下一个没有这个 bug 的主要版本预计会在 2 到 3 周左右发布

come on please fix this problem,i love this plugin and want use it immediately
