### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by 18780262934** [platz1de/EasyEdit#18]
When i load the plugin in PM4,it cause this problem,and except "//pos1 //pos2" command can not work

[14:39:29.911] [EasyEdit editing thread/ERROR]: Failed to load conversion data, schematic conversion is not available

Fatal error: Uncaught TypeError: pocketmine\utils\MainLogger::logException(): Argument #1 ($e) must be of type Throwable, string given, called in phar://C:/BaiduNetdiskDownload/Severs/plugins/EasyEdit.phar/src/platz1de/EasyEdit/schematic/BlockConvertor.php on line 60 and defined in phar://C:/BaiduNetdiskDownload/Severs/PocketMine-MP.phar/src/utils/MainLogger.php:134
Stack trace:
#0 phar://C:/BaiduNetdiskDownload/Severs/plugins/EasyEdit.phar/src/platz1de/EasyEdit/schematic/BlockConvertor.php(60): pocketmine\utils\MainLogger->logException('Operation timed...')
#1 phar://C:/BaiduNetdiskDownload/Severs/plugins/EasyEdit.phar/src/platz1de/EasyEdit/thread/input/ConfigInputData.php(45): platz1de\EasyEdit\schematic\BlockConvertor::load('https://raw.git...', 'https://raw.git...', 'https://raw.git...', 'https://raw.git...', 'https://raw.git...')
#2 phar://C:/BaiduNetdiskDownload/Severs/plugins/EasyEdit.phar/src/platz1de/EasyEdit/thread/EditThread.php(192): platz1de\EasyEdit\thread\input\ConfigInputData->handle()
#3 phar://C:/BaiduNetdiskDownload/Severs/plugins/EasyEdit.phar/src/platz1de/EasyEdit/thread/EditThread.php(58): platz1de\EasyEdit\thread\EditThread->parseInput()
#4 phar://C:/BaiduNetdiskDownload/Severs/PocketMine-MP.phar/src/thread/CommonThreadPartsTrait.php(93): platz1de\EasyEdit\thread\EditThread->onRun()
#5 [internal function]: pocketmine\thread\Thread->run()
#6 {main}
  thrown in phar://C:/BaiduNetdiskDownload/Severs/PocketMine-MP.phar/src/utils/MainLogger.php on line 134

**Comment by 18780262934** [comment]
Hi,few weeks past,this issue still hasn't been repaired,users form all the world is waiting for the update,please!

**Comment by platz1de** [comment]
It's fixed on the "dev" branch (you can grab a phar at https://poggit.pmmp.io/ci/platz1de/EasyEdit/EasyEdit if you want, these were not specifically checked / approved by poggit though).
It'll take a bit before I am ready to merge everything and make the next large release (releasing a small patch istn't reasonable in this case as it would be quite some work to backport the fixes)
