### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by DramaLvl1** [platz1de/EasyEdit#2]
Sry for my english because I mainly speak german but if I do //undo I cant use other commands like //set or //brush

**Comment by platz1de** [comment]
This sounds like it somehow crashed the whole Thread.

Are there any Errors the console?
And is this happening all the time you undo something, if not which undos trigger this problem?

**Comment by DramaLvl1** [comment]
If I write //undo this Error appears in the console:

Fatal error: Uncaught ErrorException: Trying to access array offset on value of type null in phar:///home/minecraft/pocketmine.phar/src/pocketmine/item/ItemFactory.php:318

Stack trace:

#0 phar:///home/minecraft/pocketmine.phar/src/pocketmine/item/ItemFactory.php(318): pocketmine\utils\Utils::errorExceptionHandler(8, 'Trying to acces...', 'phar:///home/mi...', 318, Array)

#1 phar:///home/minecraft/pocketmine.phar/src/pocketmine/item/ItemFactory.php(377): pocketmine\item\ItemFactory::get(7, 0)

#2 phar:///home/minecraft/pocketmine.phar/src/pocketmine/level/generator/Flat.php(123): pocketmine\item\ItemFactory::fromStringSingle('7')

#3 phar:///home/minecraft/pocketmine.phar/src/pocketmine/level/generator/Flat.php(140): pocketmine\level\generator\Flat::parseLayers('7,2x3,2')

#4 phar:///home/minecraft/pocketmine.phar/src/pocketmine/level/generator/Flat.php(87): pocketmine\level\generator\Flat->parsePreset()

#5 phar:///home/minecraft/plugins/EasyEdit.phar/src/platz1de/EasyEdit/task/EditTask.php(147): pocketmine\level\generator\Fl in phar:///home/minecraft/pocketmine.phar/src/pocketmine/item/ItemFactory.php on line 318
