### ISSUE TITLE
When you pick up a wooden axe it is as if you have written //wand

### ISSUE THREAD

**Issue by MrBlasyMSK** [platz1de/EasyEdit#23]
I just realized that if an OP wants to use a wooden axe in a normal way it will start marking positions which is a bit annoying if you want to play more "normal".
My suggestion would be that the axe should be enchanted like the BuilderTools plugin so it doesn't affect normal axes

**Comment by platz1de** [comment]
This is intended, you'll need to be in creative & have appropriate permissions to use it though.
I don't see anyone using a normal wooden axe in creative mode, so i don't feel like this is a problem, might add a config option to require a //wand axe in a feature version
