### ISSUE TITLE
Undo Bug

### ISSUE THREAD

**Issue by JohnnyX071** [platz1de/EasyEdit#3]
When I use a command like //set 0 something and after I try to use //undo, it doesn't work. It says that it pasted the blocks back but nothing happens. Nothing appears on console too. Could you please fix it?

**Comment by platz1de** [comment]
Is copy and pasting working for you?
This seems to be connected with #2, I currently can't reproduce it tho.

**Comment by JohnnyX071** [comment]
> Is copy and pasting working for you?
> This seems to be connected with #2, I currently can't reproduce it tho.

Yes it does, but //undo never works

**Comment by JohnnyX071** [comment]
Should I try the newest dev version? It might be fixed

**Comment by platz1de** [comment]
Yea would be great

**Comment by JohnnyX071** [comment]
ok

**Comment by JohnnyX071** [comment]
Even on the latest dev version //undo doesn't work
