### ISSUE TITLE
bug //fill

### ISSUE THREAD

**Issue by TukangM** [platz1de/EasyEdit#34]
when i select pos 1 and 2 with axe //wand
when //fill stone block not filling pos 1 2 range. filling 15k block or randomly 

php: 8.0.24 (compiled for arm64)
OS: KaliLinux (Chroot) (inside android)

**Comment by platz1de** [comment]
Use //set <block> to fill an area between selections, //fill is meant to be used to set blocks in an irregular shape (e.g. filling a lake with water).
The names for these commands are taken from the original WorldEdit on java edition and not from the vanilla game.
I'll look into clearifying this in the description somehow.
