### ISSUE TITLE
Where is $x, $y and $z defined in ExpandBlockFaceTask??

### ISSUE THREAD

**Issue by SwarooopDev** [platz1de/EasyEdit#36]
title

**Comment by platz1de** [comment]
https://github.com/platz1de/EasyEdit/blob/master/src/platz1de/EasyEdit/task/editing/expanding/ExtendBlockFaceTask.php#L80
I first of all can't recommend trying to extract parts of this plugin as you'll have problems to mix everything together. And also this issue tracker isn't a development Forum.

**Comment by SwarooopDev** [comment]
> https://github.com/platz1de/EasyEdit/blob/master/src/platz1de/EasyEdit/task/editing/expanding/ExtendBlockFaceTask.php#L80 I first of all can't recommend trying to extract parts of this plugin as you'll have problems to mix everything together. And also this issue tracker isn't a development Forum.

its not extracting its more like understanding
