### ISSUE TITLE
Not replacing the leaves blocks for example 18:1 the spruce leaves

### ISSUE THREAD

**Issue by LIVEGUYS** [platz1de/EasyEdit#37]
It doesn't replacing the spruceleaves when do //replace 18:1 sand 
Like that command I typed and it shows 0 block is replaced what does it means?
Please I request you to fix this problem...

**Comment by platz1de** [comment]
Try `//replace #18:1 sand`
Non-persistent leaves get currently automatically converted to persistent ones (so leaves placed by EasyEdit don't decay), this sadly also applies to //replace. This behaviour will be improved in pmmp5 to actually do what is expected.
