### ISSUE TITLE
Interact with wand doesn't work

### ISSUE THREAD

**Issue by roimee6** [platz1de/EasyEdit#38]
You can't have position 2 (interacting with a block with the axe) if there are too many players (I think that's where it comes from), but the //2 works very well

**Comment by roimee6** [comment]
Has this been fixed? If yes, in which branch?

**Comment by platz1de** [comment]
With PM5 releasing pretty soon, I have time to do another PM4 bugfix release (they often take weeks to get approved).
A fix should be out for PM5 (dev branch) soon though, as soon as its running reliably.
