### ISSUE TITLE
[Bug]: Can't copy selections

### ISSUE THREAD

**Issue by supercrafter333** [platz1de/EasyEdit#40]
Hello, everytime I try to copy something and paste it with //paste I'm getting the following message: `Die Zwischenablage ist leer.` (The clipboard is empty)

I'm using PocketMine-MP 5.0.0 on Linux Ubuntu 22.04.

**Comment by platz1de** [comment]
Does it say that blocks were copied? If it does and the count is 0, are there any warnings in the console?
If you restart the server and only select and //copy something, how many Stored selections does //status show?

**Comment by supercrafter333** [comment]
No, there're no messages in the console and I don't get a message if I type `//copy`.

### Steps to reproduce:
1. Select a area with the axe or `//pos1` and `//pos2`
2. Run the `//copy`-command
3. Try to use `//paste` ==> You'll get the following message: *The clipboard is empty.*

### Version information
PMMP: 5.0.0-BETA3+dev (git hash: 1026811741cb26bd6442b65645afa6a9b1bbc4d0)
PHP: 8.1.17
OS: Linux Ubuntu 22.04
EasyEdit: 3.0.0-alpha2

**Comment by supercrafter333** [comment]
Closed as fixed.
