### ISSUE TITLE
//Brush Issue

### ISSUE THREAD

**Issue by CoolCuzzy** [platz1de/EasyEdit#45]
Hey idk if there’s already a resolution for this but it’s very annoying, essentially whenever my builders or I use the //brush and start attempting to terraform with the brushes we create, all the things we set which are usually set to like blocks, are random blocks that don’t register on the screen unless we leave the world and rejoin the world.

like for example if I do //brush sphere 3 air all the air is levers until I leave and rejoin the world. Then it is set to air.

**Comment by CoolCuzzy** [comment]
Also happens when I do //set

**Comment by platz1de** [comment]
Sounds like the registry is somehow out of sync, can you try setting `fast-set-max` in the config to 0 and check if the issue still occurs?

**Comment by CoolCuzzy** [comment]
I restarted the server a couple of times, reinstalled the plugin and did what u told me and it eventually worked. Idk what or why but thank god
