### ISSUE TITLE
Crash when loading schematics

### ISSUE THREAD

**Issue by themalcus96** [platz1de/EasyEdit#47]
Hi. Does not allow you to insert a schematic file . The file was created using the same plugin. When loading, the message "There are no bytes left in the buffer" appears.

 [EasyEdit editing thread/CRITICAL]: pocketmine\utils\BinaryDataException: "No bytes left in buffer" (EXCEPTION) in "pmsrc/vendor/pocketmine/binaryutils/src/Binary" at line 407
--- Stack trace ---
  #0 pmsrc/plugins/EasyEdit-dev/src/platz1de/EasyEdit/schematic/type/SpongeSchematic(142): pocketmine\utils\Binary::readUnsignedVarInt(string[45671] ................................................................................, int 45671)
  #1 pmsrc/plugins/EasyEdit-dev/src/platz1de/EasyEdit/schematic/SchematicFileAdapter(53): platz1de\EasyEdit\schematic\type\SpongeSchematic::readIntoSelection(object pocketmine\nbt\tag\CompoundTag#19456, object platz1de\EasyEdit\selection\DynamicBlockListSelection#38605)
  #2 pmsrc/plugins/EasyEdit-dev/src/platz1de/EasyEdit/task/schematic/SchematicLoadTask(37): platz1de\EasyEdit\schematic\SchematicFileAdapter::readIntoSelection(string[111] C:/Users/.................. ..................../Desktop/Obnova5/PocketMine-MP/p, object platz1de\EasyEdit\selection\DynamicBlockListSelection#38605)
  #3 pmsrc/plugins/EasyEdit-dev/src/platz1de/EasyEdit/thread/EditThread(79): platz1de\EasyEdit\task\schematic\SchematicLoadTask->executeInternal()
  #4 pmsrc/src/thread/CommonThreadPartsTrait(96): platz1de\EasyEdit\thread\EditThread->onRun()
  #5 (): pocketmine\thread\Thread->run()
--- End of exception information ---

**Comment by themalcus96** [comment]
![image](https://github.com/platz1de/EasyEdit/assets/137106140/10ef6932-2c9b-4171-831a-a968b4c24640)


By testing, I came to the conclusion that if the schematic file has a number of blocks equal to less than 131 thousand, then it easily inserts. If this threshold is crossed, it already writes the error above. In the screenshot, in Russian, it is indicated where it was executed, when 130 thousand were uploaded, and when 131 thousand were uploaded.

**Comment by themalcus96** [comment]
That is, somehow no more than 1309999 blocks are stored in the buffer. I can't figure out yet where these numbers for the limit come from.

**Comment by platz1de** [comment]
Hmm this is a really weird one, old schematics are affected by this too, so definitely a problem with loading
