### ISSUE TITLE
Custom blocks

### ISSUE THREAD

**Issue by roimee6** [platz1de/EasyEdit#49]
Blocks registered by other plugins are not taken into consideration (or just don't work) when copied etc., it replaces them with info blocks.

Here's the plugin that lets me set these blocks: https://github.com/roimee6/DecorativeBlocks

And I've enabled the option in config for custom blocks
Video: https://www.youtube.com/watch?v=EOKK9euvSGY&ab_channel=MaXoooZ

**Comment by platz1de** [comment]
Thats only a visual bug, as soon as you rejoin the server, the blocks should have the proper look.
As a workaround, you can set `fast-set-max` in the config to 0

This weird behaviour should still be regarded as a bug though, so i'll keep this open

**Comment by CoolCuzzy** [comment]
did you set allow-unregistered-blocks to true? did it cause any crashes or world corruption?

**Comment by platz1de** [comment]
The `allow-unregistered-blocks` option is a relict from old versions and currently doesn't have any effect in 3.x.x

**Comment by platz1de** [comment]
Closed with b1535fc0f0d91a0626b5f0871595af89d4c25bc0
