### ISSUE TITLE
Replace Brush

### ISSUE THREAD

**Issue by CoolCuzzy** [platz1de/EasyEdit#53]
I want to create a brush that essentially I can replace things with for example

/brush sphere replace (block) (block) which can also include multiple blocks. Essentially the replace command run through a brush.

Not sure if you’ve already implemented it but if not can you do so?

**Comment by platz1de** [comment]
This can be done using [checkblock patterns](https://github.com/platz1de/EasyEdit/wiki/Checkblock-Pattern).
For example //brush sphere 10 `block;grass(stone)` would create a brush which replaces grass with stone

To replace multiple blocks you currently have to repeat the pattern: `block;grass(stone).block;dirt(stone).block;granite(stone)` (Note that they are combined using dots not commas)
