### ISSUE TITLE
Percentages

### ISSUE THREAD

**Issue by JohnnyX071** [platz1de/EasyEdit#6]
Hello, I am not sure if you have implemented it because I have been searching and I don't know how to do it. Can you do a command like: //replace grass grass 40%, stone 40%, dirt 20%? if not could you add something like that please?

**Comment by platz1de** [comment]
Currently the only way to use percentages is to repeat the wanted blocks in a random pattern:
//replace grass #random(grass,grass,stone,stone,dirt)

I really need to put some work into making this more user-friendly and add for example percentages directly

**Comment by JohnnyX071** [comment]
Ok thanks and what about a way to rotate buildings, i cannot find any command to rotate them

**Comment by platz1de** [comment]
Not possible yet, sorry

**Comment by JohnnyX071** [comment]
Are you going to add it, it is very important, I want to rotate a building 180 degrees and I can't

**Comment by platz1de** [comment]
Yes, but I don't think it will make it into the next release as I currently prioritise optimising existing features

**Comment by JohnnyX071** [comment]
hm ok, thanks

**Comment by platz1de** [comment]
This will be part of the upcoming api 4 release
(percentages and rotating)
