### ISSUE TITLE
Error on easyedit/convert/blocktagmanager line 93

### ISSUE THREAD

**Issue by LIVEGUYS** [platz1de/EasyEdit#60]
This problem 
Error: Unknown block tag 10376:136
File: plugins/EasyEdit.phar/src/platz1de/EasyEdit/convert/BlockTagManager
Line: 93
Type: pocketmine\data\bedrock\block\convert\UnsupportedBlockStateException
Backtrace:
#0 plugins/EasyEdit.phar/src/platz1de/EasyEdit/pattern/parser/PatternParser(204): platz1de\EasyEdit\convert\BlockTagManager::getTag(string[9] 10376:136, true)
#1 plugins/EasyEdit.phar/src/platz1de/EasyEdit/command/flags/BlockCommandFlag(28): platz1de\EasyEdit\pattern\parser\PatternParser::getBlockType(string[9] 10376:136, true)
#2 plugins/EasyEdit.phar/src/platz1de/EasyEdit/command/defaults/selection/ReplaceCommand(43): platz1de\EasyEdit\command\flags\BlockCommandFlag->parseArgument(object platz1de\EasyEdit\command\defaults\selection\ReplaceCommand#58465, object platz1de\EasyEdit\session\Session#137228, string[9] 10376:136)
#3 plugins/EasyEdit.phar/src/platz1de/EasyEdit/command/flags/CommandFlagParser(78): platz1de\EasyEdit\command\defaults\selection\ReplaceCommand->parseArguments(object platz1de\EasyEdit\command\flags\CommandFlagCollection#172029, object platz1de\EasyEdit\session\Session#137228, array[2])
#4 plugins/EasyEdit.phar/src/platz1de/EasyEdit/command/CommandManager(46): platz1de\EasyEdit\command\flags\CommandFlagParser::parseFlags(object platz1de\EasyEdit\command\defaults\selection\ReplaceCommand#58465, array[2], object platz1de\EasyEdit\session\Session#137228)
#5 plugins/EasyEdit.phar/src/platz1de/EasyEdit/command/EasyEditCommand(46): platz1de\EasyEdit\command\CommandManager::processCommand(object platz1de\EasyEdit\command\defaults\selection\ReplaceCommand#58465, array[2], object pocketmine\player\Player#181031)
#6 pmsrc/src/command/SimpleCommandMap(212): platz1de\EasyEdit\command\EasyEditCommand->execute(object pocketmine\player\Player#181031, string[8] /replace, array[2])
#7 pmsrc/src/Server(1415): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#181031, string[23] /replace 10376:136 sand)
#8 pmsrc/src/player/Player(1503): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#181031, string[23] /replace 10376:136 sand)
#9 pmsrc/src/network/mcpe/handler/InGamePacketHandler(818): pocketmine\player\Player->chat(string[24] //replace 10376:136 sand)
#10 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#77873)
#11 pmsrc/src/network/mcpe/NetworkSession(437): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#173913)
#12 pmsrc/src/network/mcpe/NetworkSession(381): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#77873, string[46] M.//replace 10376:136 sand..F1tJ<..k.U.fy....D)
#13 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[49] ...../J-.ILNU04067.246S(N.Ka..fX.e.C2.?.VZ..E....)
#14 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[58] ....,.y.h...^.MS.<"^.j[t..az..%f...A...F....nd...S<......Y)
#15 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#168288)
#16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#17 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#18 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#19 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1688823112.5652)
#20 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
#21 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[78] /storage/emulated/0/Android/data/com.kpwnapps.pmmpplugins/files/PocketMine-MP/, string[86] /storage/emulated/0/Android/data/com.kpwnapps.pmmpplugins/files/PocketMine-MP/pl)
#22 pmsrc/src/PocketMine(357): pocketmine\server()
#23 pmsrc(11): require(string[122] phar:///storage/emulated/0/Android/data/com.kpwnapps.pmmpplugins/files/PocketMin)

Code:
[84] 
[85] 	/**
[86] 	 * @param string $tag
[87] 	 * @param bool   $isMask Non-mask tags are only available on the main thread
[88] 	 * @return BlockGroup|MaskedBlockGroup
[89] 	 */
[90] 	public static function getTag(string $tag, bool $isMask): BlockGroup|MaskedBlockGroup
[91] 	{
[92] 		if (!isset(self::$tags[$tag])) {
[93] 			throw new UnsupportedBlockStateException("Unknown block tag $tag");
[94] 		}
[95] 		if ($isMask) {
[96] 			return new MaskedBlockGroup(self::$tags[$tag]);
[97] 		}
[98] 		return new BlockGroup(self::$tagStates[$tag]);
[99] 	}
[100] 
[101] 	public static function loadResourceData(string $rawData): void
[102] 	{
[103] 		try {

Error by easyedit line number 93 ! 
What do you mean by throw new?

**Comment by LIVEGUYS** [comment]
Should I remove the line?

**Comment by LIVEGUYS** [comment]
You mean by that blockid is need to be correct?

**Comment by platz1de** [comment]
Yea, please use this build to fix the issue: https://poggit.pmmp.io/r/217001/EasyEdit_dev-485.phar
