### ISSUE TITLE
Crash in pocketmine 5.3.0

### ISSUE THREAD

**Issue by NdaruAjaa** [platz1de/EasyEdit#66]
PocketMine-MP version: 5.3.0 [Protocol 594]
Git commit: d630b3af7bbdd5754dedd1ca4dd6e486fd3012ef
PHP version: 8.1.20
OS: Linux, linux

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: EasyEdit

Error: Undefined array key "color"
File: pmsrc/src/data/bedrock/block/upgrade/BlockStateUpgrader
Line: 89
Type: ErrorException
Backtrace:
#0 pmsrc/src/data/bedrock/block/upgrade/BlockStateUpgrader(89): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[27] Undefined array key "color", string[95] phar:///home/container/PocketMine-MP.phar/src/data/bedrock/block/upgrade/BlockSt, int 89)
#1 plugins/EasyEdit_dev-481.phar/src/platz1de/EasyEdit/thread/block/BlockStateTranslationManager(140): pocketmine\data\bedrock\block\upgrade\BlockStateUpgrader->upgrade(object pocketmine\data\bedrock\block\BlockStateData#161760)
#2 plugins/EasyEdit_dev-481.phar/src/platz1de/EasyEdit/thread/EditAdapter(13): platz1de\EasyEdit\thread\block\BlockStateTranslationManager::tick()
#3 pmsrc/src/scheduler/TaskHandler(113): platz1de\EasyEdit\thread\EditAdapter->onRun()
#4 pmsrc/src/scheduler/TaskScheduler(137): pocketmine\scheduler\TaskHandler->run()
#5 pmsrc/src/plugin/PluginManager(530): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(int 9)
#6 pmsrc/src/Server(1782): pocketmine\plugin\PluginManager->tickSchedulers(int 9)
#7 pmsrc/src/Server(1671): pocketmine\Server->tick()
#8 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
#9 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#10 pmsrc/src/PocketMine(357): pocketmine\server()
#11 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by Wyze3306** [comment]
yes please patch

**Comment by platz1de** [comment]
Restarting the server should fix it for now, concrete & shulker boxes won't behave correctly now though

**Comment by platz1de** [comment]
Are there any notices like this in your console shortly after restarting?
![grafik](https://github.com/platz1de/EasyEdit/assets/51201131/f943805a-b500-4ead-8d66-67e9213eef0f)
