### ISSUE TITLE
no bytes left in buffer

### ISSUE THREAD

**Issue by EddwardCuadra** [platz1de/EasyEdit#69]
I ran into this problem when trying to place a somewhat large schem ... I would like to know how I could have more space in the buffer, since otherwise it would only let me put quite small structures.

**Comment by platz1de** [comment]
This has already been fixed in 30756c0ee1a1c405c3de50d1114408c29b886a78
You can get the newest dev build from https://poggit.pmmp.io/ci/platz1de/EasyEdit/EasyEdit
