### ISSUE TITLE
Erro in //rotate

### ISSUE THREAD

**Issue by MateusBlackyOFC** [platz1de/EasyEdit#70]
![image](https://github.com/platz1de/EasyEdit/assets/89048733/6ea50060-8eee-4c79-ac8a-8be39e73ddd2)

I copied a certain area, and tried to use //rotate and this error came back!

I tried with several constructions!

Note: I copied and used //rotate in the same position!

**Comment by platz1de** [comment]
The should've been fixed with d02199edde9dc068dd26930c10ff3b83cec412d5
Please try the newest dev build [on poggit](https://poggit.pmmp.io/ci/platz1de/EasyEdit/EasyEdit)

**Comment by MateusBlackyOFC** [comment]
> O deveria ter sido corrigido com [d02199e](https://github.com/platz1de/EasyEdit/commit/d02199edde9dc068dd26930c10ff3b83cec412d5) Por favor, tente o mais novo dev build [no poggit](https://poggit.pmmp.io/ci/platz1de/EasyEdit/EasyEdit)

![image](https://github.com/platz1de/EasyEdit/assets/89048733/c6b75cff-51c3-4af9-88ba-0182356efbed)

**Comment by platz1de** [comment]
Blame poggit for indexing the repo wrong again...
The direct download link is https://poggit.pmmp.io/r/217001/EasyEdit_dev-485.phar, that one hopefully works
