### ISSUE TITLE
//Flip Not working

### ISSUE THREAD

**Issue by CoolCuzzy** [platz1de/EasyEdit#74]
When the command is run, an error pops up stating exactly: "Your Task crashed please report this, chunk 0 is not loaded"

Also can i get an update to see if all the other issues i brought up have been resolved? for example //rotate i saw it hasnt been merged yet since the issue hasnt closed and its kind of urgent to use. ill continue to troubleshoot and find problems for you since  i have a team of about 8 builders using your plugin xD if youd like to get into contact with me personally add me on discord through: cuzco120

**Comment by platz1de** [comment]
This was resolved in d02199edde9dc068dd26930c10ff3b83cec412d5
Use the newest dev build from poggit
