### ISSUE TITLE
Naturalize brush

### ISSUE THREAD

**Issue by SillierShark195** [platz1de/EasyEdit#75]
![Screenshot_20230816_080639_5c8300b655012b1930f2e0a7b81bf6a9](https://github.com/platz1de/EasyEdit/assets/61718146/1d2e9c1b-7378-49cb-ab28-b4016e440b30)

Middle block not change at edge

**Comment by platz1de** [comment]
The default naturalize brush is spherical
Use `//brush cy <radius> <height> nat;<block1>;<block2>;<block3>` to create a cylindrical one (i'm aware that this syntax isn't documented well enough)
