### ISSUE TITLE
Leaves not replacing! 

### ISSUE THREAD

**Issue by LIVEGUYS** [platz1de/EasyEdit#78]
When I do //replace 18 sand or //replace leaves sand or //replace oak_leaves sand it's shows on the chat 0 replaced blocks why leaves are broken or plugin pls fix this problem quickiest you can pls!

**Comment by platz1de** [comment]
Leaves are always persistent by default. The ones growing on trees aren't though, meaning they won't be affected
Use `/replace #leaves sand` to replace all kinds of leaves or if you only want to replace these specific leaves `oak_leaves[persistent=false]` should do the trick too

**Comment by LIVEGUYS** [comment]
Than //flip command does not working! 
This is the error showing in the console but the server didn't crash! 
Error - thread/CRITICAL]: Exception: "Cannot traverse an already closed generator" (EXCEPTION) in "/storage/emulated/0/Android/data/com.kpwnapps.pmmpplugins/files/PocketMine-MP/plugins/EasyEdit (1).phar/src/platz1de/EasyEdit/task/DynamicStoredFlipTask" at line 79

**Comment by platz1de** [comment]
Thats unrelated to this issue (opened #79 for that topic)
