### ISSUE TITLE
Crash! Selection changing

### ISSUE THREAD

**Issue by Neerdex** [platz1de/EasyEdit#80]
Crash when try to change one of the selected //pos.

[00:49:58.266] [Server thread/EMERGENCY]: Crash occurred while handling a packet from session: Nickname
[00:49:58.268] [Server thread/CRITICAL]: TypeError: "pocketmine\world\World::createBlockUpdatePackets(): Argument #1 ($typeConverter) must be of type pocketmine\network\mcpe\convert\TypeConverter, array given, called in phar://C:/Servers/MCPE/Ankarian-PM5/plugins/EasyEdit (2).phar/src/platz1de/EasyEdit/utils/PacketUtils.php on line 44" (EXCEPTION) in "pmsrc/src/world/World" at line 1156
--- Stack trace ---
  #0 plugins/EasyEdit (2).phar/src/platz1de/EasyEdit/utils/PacketUtils(44): pocketmine\world\World->createBlockUpdatePackets(array[1])
  #1 plugins/EasyEdit (2).phar/src/platz1de/EasyEdit/world/clientblock/StructureBlockOutline(38): platz1de\EasyEdit\utils\PacketUtils::resendBlock(object pocketmine\world\Position#197505, object pocketmine\world\World#60040, object Stats\player\MagicPlayer#181406)
  #2 plugins/EasyEdit (2).phar/src/platz1de/EasyEdit/world/clientblock/ClientSideBlockManager(36): platz1de\EasyEdit\world\clientblock\StructureBlockOutline->remove(object Stats\player\MagicPlayer#181406)
  #3 plugins/EasyEdit (2).phar/src/platz1de/EasyEdit/session/Session(276): platz1de\EasyEdit\world\clientblock\ClientSideBlockManager::unregisterBlock(string[8] Nickname, int 0)
  #4 plugins/EasyEdit (2).phar/src/platz1de/EasyEdit/session/Session(244): platz1de\EasyEdit\session\Session->updateSelectionHighlight()
  #5 plugins/EasyEdit (2).phar/src/platz1de/EasyEdit/command/defaults/selection/FirstPositionCommand(34): platz1de\EasyEdit\session\Session->selectPos1(object pocketmine\world\Position#198458)
  #6 plugins/EasyEdit (2).phar/src/platz1de/EasyEdit/command/CommandManager(47): platz1de\EasyEdit\command\defaults\selection\FirstPositionCommand->process(object platz1de\EasyEdit\session\Session#82802, object platz1de\EasyEdit\command\flags\CommandFlagCollection#198457)
  #7 plugins/EasyEdit (2).phar/src/platz1de/EasyEdit/command/EasyEditCommand(46): platz1de\EasyEdit\command\CommandManager::processCommand(object platz1de\EasyEdit\command\defaults\selection\FirstPositionCommand#42204, array[0], object Stats\player\MagicPlayer#181406)
  #8 pmsrc/src/command/SimpleCommandMap(212): platz1de\EasyEdit\command\EasyEditCommand->execute(object Stats\player\MagicPlayer#181406, string[5] /pos1, array[0])
  #9 pmsrc/src/Server(1427): pocketmine\command\SimpleCommandMap->dispatch(object Stats\player\MagicPlayer#181406, string[5] /pos1)
  #10 pmsrc/src/player/Player(1508): pocketmine\Server->dispatchCommand(object Stats\player\MagicPlayer#181406, string[5] /pos1)
  #11 pmsrc/src/network/mcpe/handler/InGamePacketHandler(856): pocketmine\player\Player->chat(string[6] //pos1)
  #12 pmsrc/vendor/nethergamesmc/bedrock-protocol/src/CommandRequestPacket(59): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#198467)
  #13 pmsrc/src/network/mcpe/NetworkSession(512): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#141566)
  #14 pmsrc/src/network/mcpe/NetworkSession(455): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#198467, string[28] M.//pos1..J....+2..j.......F)
  #15 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[74] ..e.././6d....f.-m.[.Y.l'w.f`p...X...q.........8Z.br..b...8.#.C'3.W_. ....)
  #16 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[83] ../A.M$.Z.........r....!..B....X.......:/|.TY.SB..y}r.@|.d..2j....2^...[m..Hx...)
  #17 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#184747)
  #18 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #19 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #20 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #21 pmsrc/src/Server(1687): pocketmine\snooze\SleeperHandler->sleepUntil(float 1693615798.2972)
  #22 pmsrc/src/Server(1075): pocketmine\Server->tickProcessor()
  #23 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[29] C:\Servers\MCPE\Ankarian-PM5\, string[37] C:\Servers\MCPE\Ankarian-PM5\plugins\)
  #24 pmsrc/src/PocketMine(357): pocketmine\server()
  #25 pmsrc(11): require(string[73] phar://C:/Servers/MCPE/Ankarian-PM5/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

P.S. I'm using the NetherGames fork.

**Comment by platz1de** [comment]
Forks of pmmp aren't supported
