### ISSUE TITLE
Need commands like "//mask" or "//filter"

### ISSUE THREAD

**Issue by Neerdex** [platz1de/EasyEdit#81]
I can't find any ways to filtering blocks when using brush. Is it possible to add some commands like "//mask" or "//filter"?

**Comment by platz1de** [comment]
This can be done using [checkblock patterns](https://github.com/platz1de/EasyEdit/wiki/Checkblock-Pattern)
E.g. `//brush sphere 5 block;dirt(grass_block)` would only replace dirt with grass blocks
