### ISSUE TITLE
Bug //rotate

### ISSUE THREAD

**Issue by thedrewen** [platz1de/EasyEdit#96]
When I copy an area that is too large I cannot rotate the area.

**Comment by platz1de** [comment]
Duplicate of #82 and fixed on the dev branch
Use the newest dev build from poggit

**Comment by thedrewen** [comment]
> Duplicate of #82 and fixed on the dev branch Use the newest dev build from poggit

I don't understand. Have you a link ?

**Comment by platz1de** [comment]
https://poggit.pmmp.io/r/227164/EasyEdit_dev-492.phar

**Comment by thedrewen** [comment]
thx goodbye.
