### ISSUE TITLE
Brush not working for me + Is there a discord?

### ISSUE THREAD

**Issue by Beavermon** [platz1de/EasyEdit#97]
![image](https://github.com/platz1de/EasyEdit/assets/108250433/631807ea-16e5-4adc-b65f-bb5b0e0641a2)

This is what i'm typing and the brush only displays a sand sphere. What am I doing wrong?

**Comment by platz1de** [comment]
There is an extra space in your command
`//brush sphere 7.5 sand,70%sand,30%sandstone` (gravity=false is already default too)
also you probably want to leave the first sand out completely (its the same as 170%sand,30%sandstone)

**Comment by Beavermon** [comment]
thx
