### ISSUE TITLE
How do I creeate a 104x104 1 block thick square? 

### ISSUE THREAD

**Issue by Beavermon** [platz1de/EasyEdit#98]
i've been trying to //pos1 //pos2 the coords then /fill it with dirt but it just makes a huge cube

**Comment by platz1de** [comment]
Fill isn't affected by the selected positions. Red the Readme on what the command is actually doing.

**Comment by Beavermon** [comment]
I'm still confused, what does it mean by direction?

**Comment by platz1de** [comment]
you are looking for //set

**Comment by Beavermon** [comment]
alr ty
